name: Rerun Workflow
on:
  workflow_run:
    workflows:
      - run_work.yml
    types:
      - completed

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runs: [1, 2, 3] # specify how many times to run the workflow
    steps:
      - name: Rerun Workflow
        uses: peter-evans/workflow-run-conclusion@v1
        with:
          token: secret.token
          conclusion: success
          rerun: true
