name: Rerun Workflow on Completion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Rerun workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/christian-discovery/test/actions/workflows/run_work.yml/dispatches -d '{"ref":"main"}'
