name: Rerun Workflow

on:
  workflow_run:
    types: [completed]

jobs:
  trigger-rerun:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger rerun
      uses: peter-evans/repository-dispatch@v1
      with:
        token: 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 #aayusin pa
        repository: christian-discovery/test
        event-type: trigger-rerun
