name: Rerun Workflow
on:
  workflow_run:
    workflows:
      - run_work.yml
    types:
      - completed

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Rerun Workflow
        uses: peter-evans/workflow-run-conclusion@v1
        with:
          token: secret.token
          conclusion: success
          rerun: true
