name: Trigger Workflow

on:
  workflow_run:
    workflows:
      - 'Trial'
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: secret.PAT
          repository: test
          event-type: trigger-workflow
          client-payload: '{"workflow": "My Workflow Name"}'
